// app/admin/[[...nextadmin]]/page.tsx
import { NextAdmin } from '@premieroctet/next-admin';
import { getPropsFromParams } from '@premieroctet/next-admin/dist/appRouter';
import '@premieroctet/next-admin/dist/styles.css';
import prisma from '../../../utils/client';
import schema from '../../../../prisma/json-schema/json-schema.json'; // generated by prisma-json-schema-generator on yarn run prisma generate
import { submitFormAction } from '../../actions/nextadmin';

export default async function AdminPage({ params, searchParams }) {
  const props = await getPropsFromParams({
    params: params.nextadmin,
    searchParams,
    options: {
      basePath: '/admin',
      model: {
        Event: {
          title: 'Event',
          edit: {
            fields: {
              judgingCriteria: {
                format: 'richtext-html',
              },
              rules: {
                format: 'richtext-html',
              },
              time: {
                format: 'time',
              },
            },
          },
        },
      },
    },
    prisma,
    schema,
    action: submitFormAction,
  });

  return (
    <div className='w-screen h-full text-black'>
      <NextAdmin {...props} />
    </div>
  );
}
